requirement_analysis:
  description: >
    Analyze the following user input: '{input}'.
    Access the statistics document and identify the most relevant metrics
    for this analysis. Return a JSON with the selected statistics and 
    their justifications.
  expected_output: >
    A JSON object containing:
            {
                "requirements": {
                    "position": str,  # Required player position
                    "tactical_function": str,  # Tactical role required
                    "key_characteristics": List[str]  # List of key characteristics
                },
                "primary_statistics": [
                    {
                        "name": str,  # Statistic name
                        "importance": str,  # "high", "medium", or "low"
                        "justification": str,  # Why this statistic is relevant
                        "minimum_percentile": int  # Minimum percentile required
                    }
                ],
                "secondary_statistics": [
                    # Same structure as primary_statistics
                ]
            }
  agent: interpreter_agent

data_analysis:
  description: >
    Based on the selected statistics, perform a database
    analysis to find the 20 most suitable players. Your analysis should
    consider both primary and secondary statistics, weighing them according
    to their importance. Ensure thorough statistical comparison and ranking
  expected_output: >
    A JSON object containing:
            {
                "analyzed_players": int,  # Total number of players analyzed
                "selected_players": [
                    {
                        "player_id": str,
                        "name": str,
                        "current_team": str,
                        "age": int,
                        "match_score": float,  # 0-10 score for requirement match
                        "key_statistics": {
                            "statistic_name": {
                                "value": float,
                                "percentile": int,
                                "comparison_to_requirements": str
                            }
                        },
                        "selection_justification": str
                    }
                ],
                "analysis_methodology": str  # Explanation of selection process
            }
  agent: analyst_agent

report_generation:
  description: >
    Create a detailed report based on the selected players.
    The report should include individual analysis of each player and
    justifications for their selection. Include comparative analysis
    between players and clear recommendations
  expected_output: >
    A structured report containing:
            1. Executive Summary
            2. Analysis Methodology
            3. Player Profiles (for each player):
               - Statistical Analysis
               - Tactical Fit Assessment
               - Strengths and Areas for Development
            4. Comparative Analysis
            5. Recommendations
            6. Technical Appendix with detailed statistics
  agent: report_agent

markdown_generation:
  description: >
    Format the technical report in markdown, creating a clear,
    professional, and well-organized structure. Include proper headers,
    tables, and formatting for optimal readability. Ensure all technical
    content is properly formatted and easily navigable
  expected_output: >
    A markdown file containing:
            1. Title and Table of Contents
            2. All sections from the technical report properly formatted with:
               - Consistent header hierarchy
               - Well-formatted tables for statistics
               - Proper emphasis and highlighting
               - Clear section breaks
               - Formatted lists and bullet points
            3. Save the file as 'scouting_report_{date}.md
  agent: markdown_agent